### ISSUE TITLE
[Bug]: dont get any APA 

### ISSUE THREAD

**Issue by MrMegira** [zeitlings/ubib#3]
### What happened?

hey man first of all, great workflow! just starting my phd, and it came just on time

i configured the citation styles as written in the guide you provided, and added an apa style (attached)
<img width="499" alt="2024-09-09_21 30 09" src="https://github.com/user-attachments/assets/e04e3e38-9ab7-4e51-96fb-e06d63e4e849">

also i added it through the ubib :: 
command (attached also)
<img width="849" alt="2024-09-09_21 35 58" src="https://github.com/user-attachments/assets/78a92378-6525-40e7-80ad-1fd859aa2320">

however, no matter which source i search it never suggest me the apa the apa cite style (added some examples

this is kinda accute for me, because i need to use APA most if the times. 

<img width="762" alt="2024-09-09_21 33 12" src="https://github.com/user-attachments/assets/5ef3f40f-aec1-4b24-b1bb-0fcb714b2991">
<img width="751" alt="2024-09-09_21 31 26" src="https://github.com/user-attachments/assets/113803af-aede-4ff5-987e-d91bbb34341d">

Hope i was clear, 

and again: great workflow!!

idan

### Which input causes the bug?

not sure, 

maybe something with ubib :: 

Or something in the configuration inside Alfred 

### Version

1.0.0

**Comment by zeitlings** [comment]
Hey @MrMegira 
First things first, have you checked this previous issue? https://github.com/zeitlings/ubib/issues/1
There have been problems with the APA citation style before that were not handled properly by Citeproc. Perhaps the solution I found then will work for you now as well. Let me know!

**Comment by MrMegira** [comment]
> Hey @MrMegira 
> 
> First things first, have you checked this previous issue? https://github.com/zeitlings/ubib/issues/1
> 
> There have been problems with the APA citation style before that were not handled properly by Citeproc. Perhaps the solution I found then will work for you now as well. Let me know!

Unfortunately it did not work

**Comment by zeitlings** [comment]
Could you try removing `apa,` from the configuration builder text field and just manually copy one of the cleaned styles to the data directory (as per https://github.com/zeitlings/ubib/issues/1) and tell me if that does anything?

<img width="444" alt="SCR-20240910-rboj" src="https://github.com/user-attachments/assets/7284eb3e-48e7-4f1b-a1fc-1aeda80de475">

**Comment by MrMegira** [comment]
> Could you try removing `apa,` from the configuration builder text field and just manually copy one of the cleaned styles to the data directory (as per #1) and tell me if that does anything?
> 
> <img alt="SCR-20240910-rboj" width="444" src="https://private-user-images.githubusercontent.com/25689591/366149942-7284eb3e-48e7-4f1b-a1fc-1aeda80de475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTE4MDksIm5iZiI6MTcyNTk5MTUwOSwicGF0aCI6Ii8yNTY4OTU5MS8zNjYxNDk5NDItNzI4NGViM2UtNDhlNy00ZjFiLWExZmMtMWFlZGE4MGRlNDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE4MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDRlZTMyYTAzN2ZiZTIwMjg4NGZiM2UxMTVjOGI0YTRkNWZmMDQ3NjRlZmNhMzlhYTU3ZmI1OTRkMjUzNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j5UKKh9VDB4bgZKXNOMvDmmQV6DHNigFtAIq86mjhRY">

It works! 

However, just a note that the citations provided aren’t fully aligned with the latest APA (7th edition) guidelines. It adds ‘In’ before the journal name (which isn’t necessary) and doesn’t put the volume number in parentheses. 

But I assume you don’t have control over this .

Thanks for your help

**Comment by zeitlings** [comment]
Hey @MrMegira 
Glad to hear it! Also thanks for the kind words in your first message.

> But I assume you don’t have control over this .

That's correct. The output depends on the XML file of the citation style and [Citeproc](https://github.com/cormacrelf/CiteprocRsKit), which handles the formatting. 
You could however try to [edit the file](https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step) to get the output you need.

Good luck with your PhD!
