### ISSUE TITLE
alfred-workflows-scientific/reference-importer

### ISSUE THREAD

**Issue by emraher** [zeitlings/ubib#4]
**Suggestion**
Integrate [Reference Importer](https://github.com/emraher/alfred-workflows-scientific/tree/dev/reference-importer) from [alfred-workflows-scientific](https://github.com/emraher/alfred-workflows-scientific/tree/dev/reference-importer)

**Additional context**
I have been using @andrewning's [Reference Importer](https://github.com/andrewning/alfred-workflows-scientific/tree/dev/reference-importer) for a while with slight fixes/modifications. Recently I found your workflow. [Reference Importer](https://github.com/andrewning/alfred-workflows-scientific/tree/dev/reference-importer) is not working properly. I tried to integrate it with your workflow but couldn't do it.

The idea is to add "the ability to read DOI information from PDFs and automatically file them in Bibdesk" capabilities into your workflow. Your workflow already appends citation info into Bibdesk. Maybe you can use [pdftotext](https://github.com/emraher/alfred-workflows-scientific/blob/dev/reference-importer/src/pdftotext), [pdf2doi.py](https://github.com/emraher/alfred-workflows-scientific/blob/dev/reference-importer/src/pdf2doi.py), and [common.py](https://github.com/emraher/alfred-workflows-scientific/blob/dev/reference-importer/src/common.py) files to make it possible.

@soto97 might also be interested in this integration since he also tried to fix Reference Importer as seen in this [issue](https://github.com/andrewning/alfred-workflows-scientific/issues/17).

**Comment by zeitlings** [comment]
Hi @emraher 

Thanks for the suggestion! I'm using DEVONthink to manage my documents, which has automatic DOI retrieval.
My [DEVONthink Portal](https://github.com/zeitlings/alfred-devonthink#plugins) workflow has a plugin to get the BibTeX reference via µBib, which then can be appended to the `.bib` file as plain text (there is no special consideration of Bibdesk). This is the way I'm handling reference importing. 

If you're not using DEVONthink, I'd suggest to employ the same strategy: To create a new auxiliary workflow that retrieves DOI information and calls µBib via Alfred's [External Trigger](https://www.alfredapp.com/help/workflows/outputs/call-external-trigger/) (with identifier: `init`). 

I might create this auxiliary workflow at some point, but it's currently low priority. Alternatively, I could help you set it up yourself. The [Alfred forums](https://www.alfredforum.com/) are a good place to start and get help by the community.

**Comment by emraher** [comment]
Thanks for your reply. I will check your [DEVONthink Portal](https://github.com/zeitlings/alfred-devonthink#plugins) workflow.

**Comment by zeitlings** [comment]
Hey @emraher 

I've been pondering this again and realized that there is a fairly low effort approach to implementing this. 
In `v1.2.0`, you can now find the "Elicitor" component, i.e. a utility to send PDFs to the workflow's Universal Action and get its reference that way, given a DOI could be matched.
